- alias: Spotify Volume (Set)
  trigger:
    platform: state
    entity_id: input_number.spotify_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.spotify
      volume_level: '{{  states.input_number.spotify_volume.state | int / 100  }}'
  id: b642e587008142c684c7c199947c8660
- alias: Spotify Volume (Sync)
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.spotify_volume
  action:
  - delay:
      seconds: 5
  - service: input_number.set_value
    data_template:
      entity_id: input_number.spotify_volume
      value: '{{  states.sensor.spotify_volume.state | float | round(2) * 100  }}'
  id: 650d1cdf9cb44eda91f74f8c0990451b
- alias: Spotify Shuffle (Set)
  trigger:
    platform: state
    entity_id: input_boolean.spotify_shuffle
  action:
    service: media_player.shuffle_set
    data_template:
      entity_id: media_player.spotify
      shuffle: '{% if is_state(''input_boolean.spotify_shuffle'', ''off'') %} false
        {% elif is_state(''input_boolean.spotify_shuffle'', ''on'') %} true {% endif
        %}

        '
  id: dffe6f20db7e401893532f645358b3dd
- alias: Spotify Shuffle (Sync)
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.spotify_shuffle
  action:
  - delay:
      seconds: 5
  - service_template: "{% if states.sensor.spotify_shuffle.state == 'False' %}\n \
      \ input_boolean.turn_off\n{% else %}\n  input_boolean.turn_on\n{% endif %}\n"
    data:
      entity_id: input_boolean.spotify_shuffle
  id: d313fc4e1c694b1baa2c2807896cbbb7
- id: '1530564148457'
  alias: 'Notificar: Luz Sonoff'
  trigger:
  - entity_id: switch.sonoff
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: switch.sonoff
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: ' {% if is_state(''switch.sonoff'', ''on'') %}Ligada{% else %}Desligada{%
        endif %}!'
      title: '*Luz Sonoff *'
    service: notify.telegrambot
  initial_state: 'off'
- alias: Programação do Alarme
  hide_entity: false
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_clock_time_long.state
      }}'
  condition:
    condition: state
    entity_id: input_boolean.alarm_clock_status
    state: 'on'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home
      volume_level: '{{ states.input_number.alarm_clock_volume.state }}'
  - service: tts.google_say
    entity_id: media_player.google_home
    data_template:
      message: '{{ states.input_text.text_clock.state }}'
  - delay:
      seconds: 6
  - service: tts.google_say
    data_template:
      entity_id: media_player.google_home
      message: 'Previsão para as próximas 24h é: {{ states.sensor.dark_sky_hourly_summary.state
        }} . Já para os próximos dias é {{ states.sensor.dark_sky_daily_summary.state
        }} '
  - delay:
      seconds: 25
  - service: media_extractor.play_media
    entity_id: media_player.google_home
    data_template:
      media_content_id: '{{ states.input_text.text_url_youtube.state }}'
      media_content_type: video/youtube
  id: e42ceff3366d4250a6fdefb5db6d3627
- alias: Demonstração Alarme
  initial_state: 'off'
  trigger:
  - platform: state
    entity_id: input_text.text_clock
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home
      volume_level: '{{ states.input_number.alarm_clock_volume.state }}'
  - service: tts.google_say
    data_template:
      entity_id: media_player.google_home
      message: '{{ states.input_text.text_clock.state }}'
  id: f9f88f2aaed1436797d388a1df25d2f1
- alias: Programacao Temperatura Ar (IR)
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_number.temperatura_ar
  action:
  - service: switch.broadlink_send_packet_100_64_0_26
    data_template:
      packet: "{% if is_state(\"input_number.temperatura_ar\", \"17.0\") %}\n  - 'JgDKAI+PETUQFBA2ETYQFBATEDcREhAUETYQExESETYQNxATEDcRExESERIRNhA3EDYTNBI1ETYQNhA3ERIRExESERMQExETEBMQFBATETYSERAUERIQNxE2EjQQNxESETYRNhE2EKqNkBE2EBMQNxA2ERMQExE2EBQQExA3EBMRExE1ETYQFBA2ERMREhETEDcQNhA3EDcRNRA3EDcRNRETEBMRExATERMQExETEBMRExI0ERMQExETETYQNhE2ETUSEhA2ETcQNhAADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"18.0\") %}\n  - 'JgDKAI2QEDYSEhE2EDYRExESEDcQExETEDcQExAUETUQNxATETYSEhESEBQQNBM2ETYQNhI1ETYQNhI1ERMSERETEBMQFBESEBQQExA2ETYRExATEBQQNxA2ETYREhETETURNhE2EKiQjxI1ERIQNxE2EBMQFBA2EBQREhA3EBQQExE2EDYRExE2EBMSEhATEDcQNhA3EDcQNhE2EDcQNxATEBMRExATERMQExETERIRNBI3EBMQFBATEDcRNhAzExQQExA3EDYRNhAADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"19.0\") %}\n  - 'JgDKAI6PETURExA2EjURExATETYREhETETYREhESETYRNhESETYRExATERIRNhE2EDYRNhA3ETYRNRE2ERIRExESERMREhAUERIRNhE2EDYQFBESERMQNhE2ERMQExMQETYRNhA3EKqNkBE2ERIRNhE2ERIQExE2ERMREhA3ERIRExE1EjURExE1ERMREhETEDcRNRI1EDYSNRE2ETYRNRETEBMRExATEBQREhETETURNhA2EhIQFBESETYRNRISEBMQFBE2ETURNhAADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"20.0\") %}\n  - 'JgDKAI2QETUQFBA3EDURFBESETYREhAUEDcREhETETURMxQSETYRExATEBQSNBE2EDYRNhE2EDcRNRI1ERIRExESEhIREhETERIRNhETETUQFBESERMQNhE2EBQRNRETETYQNhE2EaqOjxE2ERIQNxA3EBMQFBE1EBQQExE2ERIRExE2ETURExI1ERIQFBATEDcRNRE2EDcRNRA3ETYRNRETERIRExATERMREhETEDYRExE2ERIRExESEDcQNhETETYQExE2ETYQNhAADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"21.0\") %}\n  - 'JgDKAI2PETYQFBEzEzYREhETETURExESEjURExESETYRNRETETYQExETERIRNhE1ETYRNhA2ETYRNhA2ERMQExETERIRExATETYRNhESETYREhAUERIRNhESERMRNhESEDcQNhE2EKuOjxA3EBMRNhE2ERIQFBE1EBQREhE2ERMREhA3ETURExE2EBMQFBESETYRNRE2ETYRNRE2ETYRNRETEBMRExESERMREhE2ETYQExE2ERIRExATETYQExETETYREhA3ETURNhAADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"22.0\") %}\n  - 'JgDKAI2PEjURExA2ETYQExETEDcREhETETUTERESETYRNhESEDcREhETEBMRNhA3EDYRNhE1ETYRNhA3ERIRExESEBMRExATETYRNhE2ETURExESERMRNRETERIQFBESEDcRNRE2EKuNjxE2ERISNRE2ERIRExE1ERMQExE2EBQREhE2EDYRExA3ERIQFBESETYQNhE2ETYRNRE2EDcRNRETERIQFBESERMQExA3ETYRNRE2ERIRExESETYRExATERIRExA2EjURNhAADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"23.0\") %}\n  - 'JgDKAI6PEjURExE1ETYQExETETYREhETETURExESETYRNhATEDQUEhETERIRNhE2ETURNhE2ETURNhA3ERIRExESERMREhAUETURExE2ETUQFBESERMRNRETEDcREhESEjURNhE1EaiQkBE1ERMQNxE1ERMQExA3ERIRExE1EhIREhE2ETYQExE2ERIRExATETYRNhE1ETYRNhE1ETYRNhATEBQREhETERIRExE1ERMRNhE1ERMREhAUEDYRExE2EBMQFBE1ETYRNhAADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"24.0\") %}\n  - 'JgDOAAkACkCNjxI1ERMRNRI1ERIRExE0ExIQFBE1ERMQExA3EDcREhE2ERIRExESETYRNhE1ETYRNhA2ETYRMxQSERMREhETERIRExE1ERMREhE2ERIQFBESEDcREhE2ETYREhA3ETYRNRGrjZARNRETETURNhETERIRNhATERMRNRETERIRNhE2EBMRNhESERMREhE2ETYRNRE2ETYRNRE0EzYREhETEBMRExATERMQNhETERIRNhESERMQExE2ERMQNhE2ERIRNhE2ETQTAA0FAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"25.0\") %}\n  - 'JgDKAI2QETYQExE2ETURExESETYRExESETQTEhETETURNhETETURExESERMRNRE2ETYRNRE2ETYQNxE1ERMQExETEBMQFBA2EDcREhAUEzMSEhESERMREhETETYSNBETETURNhE2EamOjxE2EBMRNhE2EhERExA2ERMQExE2EBMSEhE2EDYRExE2ERIRExATEDcRNRE2ETYQNhE2ETYRNRETERIQFBATEBQRNRI1ERMREhA3EhERExESERMQExA3ETURExA3ETUQNxAADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"26.0\") %}\n  - 'JgDKAI2QETYQExE2ETUSEhATETYRExATEDcREhETEDYRNhETEDYRExESERMRNRI1ETYRNRE2ETYRNhE1ERMREhETEBMRExE1ETYREhE2ETYREhETERIQFBESETYQExETETURNhE2EKqPjhE2ERIQNxE2ERIQExI1EBQREhA3ERIRExE2ETURExI0ERMREhETETYRNRE2ETUSNRI1ETYRNRAUERIRExATERMRNRE2ExARNhE2EBMQFBESERMQExE2ERIRExE1ETYQNxAADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"27.0\") %}\n  - 'JgDKAI2QETURExE2ETURExESEDcREhETEDYSEhESEDcQNxESETYREhMRERIQNxE2ETQSNRE3ETURNhE2EBMRExESERIRExE2EhEQFBA2EDcTEBETERIQFBA2EjURExESEDcQNhE2EaqNjxE2ERIRNhA3ERIRExE1ERMREhE2ERMQExA3ETURExE2EBMRExATETYRNRE2ETYRNRA3ETYRNRISERIRExESERMRNRETERIRNhE0ExIRExATERMRNRE2ERIRExA3EDYRNhEADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"28.0\") %}\n  - 'JgDKAIyREDYRExA3EDYRExESETYREhAUETUSEhESETYRNhESEDcREhETERIRNhE2ETURNhE2ETUSNRA3ERIQFBESERMREhA3EBMQFBATETYREhETEBMQFBA3ETURNhATETYRNhE1EauOjxE1ERMQNhE2ERMREhA3EBMQFBE1ERMREhE2ETURExE2ERIRExATETYRNhA2ETQSNxA2ETYRNhESERMQExETEBMQNxIREBQREhA3ERIRExATERMQNxE1ETYREhE2ETYQNhEADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"29.0\") %}\n  - 'JgDKAI6QEDYRExE1ETYREhETETYREhETEDYRExESEDcRNhESEDcREhETERITNBE2ETUQNxE1ETYRNhA3ERIRExESERMREhA3EBMQNxESETYRExESERMREhE2ERIRNhAUEDYRNhE2EaqOjxI0ERMRNhA2ERMREhE2ERIRExE2ERIRExE1EDcREhE2ERMREhETETURNhE2ETMTNhA3ETURNhESERMREhETERIRNhESETYRExE1ERMREhETERIRNhETETURExE2ETURNhAADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% elif is_state(\"input_number.temperatura_ar\", \"30.0\") %}\n  - 'JgDKAI2QETYREhA3ETYQExETEDYRExESETYRExESETYRNRETETYREhETEBMQNhI1ETYRNRI1EDcRNhE1ERMREhETERIQFBE1ERMRNhE1ETYREhETEBMRExE2ERIQFBATEDcQNhE2EKyOjhE2ERIRNRI2ERIQFBE1ERMREhA3ERMQExE2ETUQFBA3ERIRExESETYRNRE2ETYRNRE2EzQRNRETEBMRExESERMRNRISEDcRNRE2ERIRExESERMRNhESERMREhA3EDQUNRAADQUAAAAAAAAAAAAAAAAAAA=='\n\
        {% else %}\n  none\n{% endif %}\n"
  id: bc0f622eff874a488fad2da85db094b4
- alias: Falar a Temperatura do Ar
  initial_state: 'off'
  trigger:
  - platform: state
    entity_id: input_number.temperatura_ar
  action:
  - service: tts.google_say
    data_template:
      entity_id: media_player.google_home
      message: "{% if is_state(\"input_number.temperatura_ar\", \"17.0\") %}\n  Temperatura\
        \ em 17 graus. Vamos congelar!\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"18.0\") %}\n  Temperatura em 19 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"19.0\") %}\n  Temperatura em 19 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"20.0\") %}\n  Temperatura em 20 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"21.0\") %}\n  Temperatura em 21 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"22.0\") %}\n  Temperatura em 22 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"23.0\") %}\n  Temperatura em 23 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"24.0\") %}\n  Temperatura em 24 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"25.0\") %}\n  Temperatura em 25 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"26.0\") %}\n  Temperatura em 26 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"27.0\") %}\n  Temperatura em 27 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"28.0\") %}\n  Temperatura em 28 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"29.0\") %}\n  Temperatura em 29 graus.\n{% elif is_state(\"input_number.temperatura_ar\"\
        , \"30.0\") %}\n  Temperatura em 30 graus. Vamos pegar fogo!\n{% else %}\n\
        \  Temperatura erro.\n{% endif %}\n"
  id: dbdfb3f19fb64fa984bd4376ee5f2996
- alias: x Notificar quando o alarme for ativado
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarme_da_casa
    to: armed_away
  - platform: state
    entity_id: alarm_control_panel.alarme_da_casa
    to: armed_home
  action:
  - service: notify.telegrambot
    data:
      message: Alarme ativado {% if is_state('alarm_control_panel.alarme_da_casa',
        'armed_away') %}com delay de 30s.{% else %}instantaneamente.{% endif %}
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home
      volume_level: 0.6
  - service: tts.google_say
    data_template:
      entity_id: media_player.google_home
      message: Alarme ativado
  id: a194fbd4c3a54c4f8ce9b25cb20cf83e
- alias: x Notificar que o alarme será ativado
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarme_da_casa
    to: pending
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home
      volume_level: 0.6
  - service: tts.google_say
    data_template:
      entity_id: media_player.google_home
      message: Alarme será ativado em 30 segundos.
  id: c7430e98aaf24939a7a589ccb24583c4
- alias: x Notificar quando o alarme for desativado
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarme_da_casa
    to: disarmed
  action:
  - service: notify.telegrambot
    data:
      message: Alarme desativado!
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home
      volume_level: 0.6
  - service: tts.google_say
    data_template:
      entity_id: media_player.google_home
      message: Alarme desativado!
  id: e732bdac555f48b2a96add2d8648fcb6
- id: '1532298569790'
  alias: x Alarme dispara
  trigger:
  - entity_id: switch.sonoff
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_da_casa
    state: armed_away
  - condition: state
    entity_id: alarm_control_panel.alarme_da_casa
    state: armed_home
  action:
  - data:
      message: Alarme disparado
    service: notify.telegrambot
