homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -00.00000
  longitude: -00.000000
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo
  # Customization file
  customize: !include customize.yaml

  auth_providers:
    - type: homeassistant
  whitelist_external_dirs:
    - /tmp
    - /config
zone:
  - name: "Trabalho"
    latitude: -00.00000
    longitude: -00.00000
    radius: 100
    icon: mdi:briefcase

  - name: "Backbone"
    latitude: -00.00000
    longitude: -00.00000
    radius: 100
    icon: mdi:briefcase


scene:
  - name: "Suíte Romantica"
    entities:
      light.abajur_da_suite:
        state: true
        rgb_color: [255, 0, 255]
        brightness: 255

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Historico 7 Dias
recorder:
  purge_keep_days: 7

http:
  base_url: https://minhacasa.meudominio.com.br:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem


updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sensor.last_boot
      - sensor.date

# View all events in a logbook
logbook:
  include:
    domains:
      - sensor
      - switch
      - media_player
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


# Sensores
sensor: !include sensor.yaml

binary_sensor: !include binary_sensor.yaml

logger:
  default: error
  logs:
    homeassistant.components.mqtt: critical


# Text to speech
tts:
  - platform: voicerss
    api_key: !secret voicerss_key
    language: 'pt-br'
    format: '44khz_16bit_stereo'
  - platform: google
    language: 'pt-br'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# Cloud
cloud:

# Localizador
device_tracker:
  - platform: google_maps
    username: !secret gmail_user
    password: !secret gmail_senha

# Player
media_extractor:

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: lg_netcast
    name: "LG Smart TV"
    host: 100.64.0.15
    access_token: 123456

# Googles home e chromecast
cast:
  media_player:
  - host: 100.64.0.20
  - host: 100.64.0.21
  - host: 100.64.0.22
  - host: 100.64.0.19


# Mosquito
mqtt:
   broker: core-mosquitto
   username: !secret mqtt_username
   password: !secret mqtt_password

# Luzes
light: !include light.yaml

# Interruptores
switch: !include switch.yaml

# Inputs text
input_text:
  text_clock:
    name: Mensagem
    initial: Bom dia! São 7 horas
  text_url_youtube:
    name: URL Youtube
    initial: https://www.youtube.com/watch?v=fvrogxMHmlg


input_datetime:
  poste_on:
    name: "Ligar poste às"
    has_date: false
    has_time: true
    initial: "19:30"
  poste_off:
    name: "Desligar poste às"
    has_date: false
    has_time: true
    initial: "23:00"
  arandelas_on:
    name: "Ligar arandelas às"
    has_date: false
    has_time: true
    initial: "19:30"
  arandelas_off:
    name: "Desligar arandelas às"
    has_date: false
    has_time: true
    initial: "23:00"

# Inputs number
input_number:
  alarm_clock_hour:
    name: Hora
    icon: mdi:timer
    initial: 7
    min: 0
    max: 23
    step: 1
    mode: slider
  alarm_clock_minutes:
    name: Minuto
    icon: mdi:timer
    initial: 0
    min: 0
    max: 59
    step: 1
    mode: slider
  alarm_clock_volume:
    name: Volume
    icon: mdi:timer
    initial: 0.40
    min: 0
    max: 0.99
    step: 0.10
    mode: slider
  temperatura_ar:
    name: 'Temperatura (On)'
    icon: mdi:temperature-celsius
    initial: 22
    min: 17
    max: 30
    step: 1
    mode: slider


# Inputs boolean
input_boolean:
  alarm_clock_status:
    name: Status
    initial: on

ffmpeg:

camera:
  - platform: ffmpeg
    name: Camera Interna
    input: rtsp://admin:senha@100.64.0.52/onvif2
  - platform: ffmpeg
    input: rtsp://admin:senha@100.64.0.60/2
    name: "Wanscam 360"


google_assistant:
  project_id: !secret google_project
  api_key: !secret google_key
  exposed_domains:
    - switch
    - light
    - script

notify:
  - name: telegramrudi
    platform: telegram
    chat_id: !secret tg_chat_idr
  - name: telegramflavia
    platform: telegram
    chat_id: !secret tg_chat_idf

telegram_bot:
  platform: polling
  api_key: !secret tg_api
  allowed_chat_ids:
    - !secret tg_chat_idr
    - !secret tg_chat_idf

alarm_control_panel:
  - platform: manual
    name: Alarme da Casa
    code: 123
    pending_time: 10
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

shopping_list:

weather:
  - platform: darksky
    api_key: !secret api_darksky

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
