homeassistant:
  name: Home
  latitude: -00.000000
  longitude: -00.000000
  elevation: 0
  unit_system: metric
  time_zone: America/Sao_Paulo
  customize: !include customize.yaml

  auth_providers:
    - type: homeassistant
  whitelist_external_dirs:
    - /tmp

zone:
  - name: "SpeedRS Casa"
    latitude: -00.000000
    longitude: -00.000000
    radius: 100
    icon: mdi:briefcase

  - name: "SpeedRS Torre"
    latitude: -00.000000
    longitude: -00.000000
    radius: 100
    icon: mdi:briefcase

  - name: "Maria João"
    latitude: -00.000000
    longitude: -00.000000
    radius: 100
    icon: mdi:briefcase

  - name: "Casa Pai"
    latitude: -00.000000
    longitude: -00.000000
    radius: 400
    icon: mdi:home-variant

scene:
  - name: "Suíte Romantica"
    entities:
      light.abajur_da_suite:
        state: true
        rgb_color: [255, 0, 255]
        brightness: 255

# Show links to resources in log and frontend
#introduction:

frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html

panel_custom:
  - name: floorplan
    sidebar_title: Planta Baixa
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config: !include floorplan.yaml

config:

recorder:
  purge_keep_days: 2

http:
  base_url: https://xxxxxx.xxxxx.com.br:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sensor.last_boot
      - sensor.date

# View all events in a logbook
logbook:
  include:
    domains:
      - sensor
      - switch
      - media_player
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


# Sensores
sensor: !include sensor.yaml

binary_sensor: !include binary_sensor.yaml


#logger:
#  default: debug

# Text to speech
tts:
# http://www.voicerss.org/personel/statistic.aspx
  - platform: voicerss
    api_key: a0000000000000000000000000000000000b
    language: 'pt-br'
    format: '44khz_16bit_stereo'
# Google (google_say)
  - platform: google
    language: 'pt-br'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# Cloud
cloud:

# Editor
#panel_iframe:
#  tasmotaadm:
#    title: Tasmota ADM
#    url: http://100.100.0.2:9541
#    icon: mdi:pulse
#  configurator:
#    title: Editor
#    icon: mdi:wrench
#    url: http://100.100.0.2:3218

# Localizador
device_tracker:
  - platform: google_maps
    username: !secret gmail_user
    password: !secret gmail_senha

# Player
media_extractor:

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: lg_netcast
    name: "LG Smart TV"
    host: 100.64.0.15
    access_token: 431855

cast:
  media_player:
  - host: 100.64.0.20
  - host: 100.64.0.21
  - host: 100.64.0.22
  - host: 100.64.0.19


# Mosquito
mqtt:
   broker: core-mosquitto
   username: !secret mqtt_username
   password: !secret mqtt_password

light: !include light.yaml

switch: !include switch.yaml

# Inputs text
input_text:
  text_clock:
    name: Mensagem
    initial: Bom dia! São 7 horas
  text_url_youtube:
    name: URL Youtube
    initial: https://www.youtube.com/watch?v=wuLKvcn-c7A

# Inputs number
input_number:
  spotify_volume:
    name: Volume
    icon: mdi:volume-high
    initial: 100
    min: 0
    max: 100
    step: 1
  alarm_clock_hour:
    name: Hora
    icon: mdi:timer
    initial: 7
    min: 0
    max: 23
    step: 1
    mode: slider
  alarm_clock_minutes:
    name: Minuto
    icon: mdi:timer
    initial: 0
    min: 0
    max: 59
    step: 1
    mode: slider
  alarm_clock_volume:
    name: Volume
    icon: mdi:timer
    initial: 0.40
    min: 0
    max: 0.99
    step: 0.10
    mode: slider
  temperatura_ar:
    name: 'Temperatura (On)'
    icon: mdi:temperature-celsius
    initial: 22
    min: 17
    max: 30
    step: 1
    mode: slider

# Inputs select
input_select:
  spotify_playlist:
    name: 'Playlist:'
    options:
      - Classicas da Zona
      - Gauderias
      - 50+ Brasil
      - Bandinhas
      - Sertanejo
      - Rock Sussa
      - Classic Rock
      - Rock Nacional
      - Metallica Tops
    icon: mdi:spotify

# Inputs boolean
input_boolean:
  spotify_shuffle:
    name: Shuffle
    icon: mdi:shuffle-variant
  alarm_clock_status:
    name: Status
    initial: on

ffmpeg:
#  run_test: false

camera:
  - platform: ffmpeg
    name: Camera Interna
    input: rtsp://admin:senha@100.64.0.100/onvif2
  - platform: ffmpeg
    input: rtsp://admin:senha@100.64.0.101/2
    name: "Wanscam 360"

google_assistant:
  project_id: !secret gg_project_id
  api_key: !secret gg_api_key
  exposed_domains:
    - switch
    - light
    - group
    - script

notify:
  - name: telegramrudi
    platform: telegram
    chat_id: !secret tg_chat_idr
  - name: telegramflavia
    platform: telegram
    chat_id: !secret tg_chat_idf

telegram_bot:
  platform: polling
  api_key: !secret tg_api_key
  allowed_chat_ids:
    - !secret tg_chat_idr
    - !secret tg_chat_idf

alarm_control_panel:
  - platform: manual
    name: Alarme da Casa
    code: 123
    pending_time: 10
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

shopping_list:

#weather:
#  - platform: darksky
#    api_key: !secret api_darksky

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
